name: semgrep Workflow

 

on:
  pull_request:
  push:
  workflow_dispatch:

 

jobs:
  analyse-code:
    runs-on: ubuntu-latest

 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

 

 

    - name: Analyse Dockerfile avec semgrep
      run: |
        docker run --rm -i semgrep/semgrep < ./super_calculator/Dockerfile

 
 
